// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project13.Stats.Core.Data;

#nullable disable

namespace Project13.Stats.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251214124456_firstMig3")]
    partial class firstMig3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project13.Stats.Core.Models.CalculationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Antal13")
                        .HasColumnType("int");

                    b.Property<int>("AntalMellanFavoriter")
                        .HasColumnType("int");

                    b.Property<int>("AntalMellanFavoriterVinst")
                        .HasColumnType("int");

                    b.Property<int>("AntalSkrällar")
                        .HasColumnType("int");

                    b.Property<int>("AntalStorfavoriter")
                        .HasColumnType("int");

                    b.Property<int>("AntalStorfavoriterVinst")
                        .HasColumnType("int");

                    b.Property<decimal>("DisagreementTop3Sum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FavoritIndexProcent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FolketsFelProcent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KvotFavoritRad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaxDisagreement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MeanDisagreement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MellanFavoritTraffProcent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MultipliceradeOddsMarknad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MultipliceradeOddsSvFolket")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OddsFavoritrad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OddsFavoritradSvF")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OddsKvotPerMatch")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OddsKvotTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OddsetFelProcent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Omsattning")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SkrallIndexProcent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StorFavoritTraffProcent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SvSpelInfoId")
                        .HasColumnType("int");

                    b.Property<string>("Tips")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotDiff")
                        .HasColumnType("int");

                    b.Property<int>("TotFavoriter")
                        .HasColumnType("int");

                    b.Property<int>("TotVinstFav")
                        .HasColumnType("int");

                    b.Property<decimal?>("Utdelning13")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Vecka")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Calculations");
                });

            modelBuilder.Entity("Project13.Stats.Core.Models.Detaljer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bortalag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Bortaresultat")
                        .HasColumnType("int");

                    b.Property<int?>("ExpertWasRight")
                        .HasColumnType("int");

                    b.Property<string>("Experttips")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hemmalag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Hemmaresultat")
                        .HasColumnType("int");

                    b.Property<int>("Matchnummer")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Matchstart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Matchstatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Oddset1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Oddset2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OddsetDiff")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OddsetHigh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OddsetLow")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OddsetProcent1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OddsetProcent2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OddsetProcentX")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("OddsetRank")
                        .HasColumnType("int");

                    b.Property<int?>("OddsetWasRight")
                        .HasColumnType("int");

                    b.Property<int?>("OddsetWasWrong")
                        .HasColumnType("int");

                    b.Property<decimal?>("OddsetX")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Omg")
                        .HasColumnType("int");

                    b.Property<decimal?>("PeopleDiff")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PeopleHigh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PeopleLow")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PeopleRank")
                        .HasColumnType("int");

                    b.Property<int?>("PeopleWasRight")
                        .HasColumnType("int");

                    b.Property<int?>("PeopleWasWrong")
                        .HasColumnType("int");

                    b.Property<string>("Produktnamn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SummeringId")
                        .HasColumnType("int");

                    b.Property<int>("SvSpelInfoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("SvenskaFolket1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SvenskaFolket2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SvenskaFolketOdds1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SvenskaFolketOdds2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SvenskaFolketOddsX")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SvenskaFolketX")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TioTidningar1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TioTidningar2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TioTidningarX")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Utfall")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vecka")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SummeringId");

                    b.ToTable("Detaljer");
                });

            modelBuilder.Entity("Project13.Stats.Core.Models.MatchEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bortalag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CalculationModelId")
                        .HasColumnType("int");

                    b.Property<decimal>("Disagreement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Hemmalag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Matchnummer")
                        .HasColumnType("int");

                    b.Property<decimal?>("Oddset1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Oddset2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OddsetX")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SvenskaFolket1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SvenskaFolket2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SvenskaFolketX")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Utfall")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CalculationModelId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Project13.Stats.Core.Models.Summering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Ant10")
                        .HasColumnType("int");

                    b.Property<int?>("Ant11")
                        .HasColumnType("int");

                    b.Property<int?>("Ant12")
                        .HasColumnType("int");

                    b.Property<int?>("Ant13")
                        .HasColumnType("int");

                    b.Property<string>("CorrectRow")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Count1")
                        .HasColumnType("int");

                    b.Property<int?>("Count2")
                        .HasColumnType("int");

                    b.Property<int?>("CountX")
                        .HasColumnType("int");

                    b.Property<decimal?>("Odds1Ok")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Odds2Ok")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Odds3Ok")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OddsetDiffSum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OddsetMaxSum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OddsetMinSum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OddsetSum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("OddsetWasRight")
                        .HasColumnType("int");

                    b.Property<int?>("OddsetWasWrong")
                        .HasColumnType("int");

                    b.Property<decimal?>("People1Ok")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("People2Ok")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("People3Ok")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PeopleDiffSum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PeopleMaxSum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PeopleMinSum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PeopleSum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PeopleWasRight")
                        .HasColumnType("int");

                    b.Property<int?>("PeopleWasWrong")
                        .HasColumnType("int");

                    b.Property<string>("Produktnamn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RandomResults")
                        .HasColumnType("int");

                    b.Property<int>("SvSpelInfoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Turnover")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Utd10")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Utd11")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Utd12")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Utd13")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Vecka")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Summering");
                });

            modelBuilder.Entity("Project13.Stats.Core.Models.Detaljer", b =>
                {
                    b.HasOne("Project13.Stats.Core.Models.Summering", "Summering")
                        .WithMany("Matches")
                        .HasForeignKey("SummeringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Summering");
                });

            modelBuilder.Entity("Project13.Stats.Core.Models.MatchEntity", b =>
                {
                    b.HasOne("Project13.Stats.Core.Models.CalculationModel", "CalculationModel")
                        .WithMany("Matcher")
                        .HasForeignKey("CalculationModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalculationModel");
                });

            modelBuilder.Entity("Project13.Stats.Core.Models.CalculationModel", b =>
                {
                    b.Navigation("Matcher");
                });

            modelBuilder.Entity("Project13.Stats.Core.Models.Summering", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
